board/urls.py
from django.urls import path

from .views import writing_views, comment_views

app_name = 'board'
urlpatterns = [
    # writing_views
    path('', writing_views.index, name='index'),
    path('create/', writing_views.create, name='create'),
    path('<int:board_pk>/', writing_views.detail, name='detail'),
    path('<int:board_pk>/update/', writing_views.update, name='update'),
    path('<int:board_pk>/delete/', writing_views.delete, name='delete'),

    # comment_views
    path('<int:board_pk>/comment/create', comment_views.create, name='comment_create'),
    # path('<int:board_pk>/comment/<int:comment_pk>/delete/', comment_views.comment_delete, name='comment_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from index import views as index_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Writing(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    writing = models.ForeignKey(Writing, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    comment = models.ForeignKey('self', on_delete=models.CASCADE, related_name='recomments', null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

board/forms.py
from django import forms

from .models import Writing, Comment


class WritingForm(forms.ModelForm):
    class Meta:
        model = Writing
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'title': '제목',
            'content': '내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control col'}),
        }
        labels = {
            'content': '댓글',
        }

board/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import (require_http_methods, require_POST,
                                          require_safe)

from .forms import WritingForm
from .models import Writing


# board create, read
@require_safe
def index(request):
    """list writing

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    writings = Writing.objects.order_by('-pk')
    page = request.GET.get('page', '1')
    paginator = Paginator(writings, 20)
    page_obj = paginator.get_page(page)
    context = {
        'writings': page_obj,
    }
    return render(request, 'board/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    """create writing

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    if request.method == 'POST':
        writing_form = WritingForm(request.POST)
        if writing_form.is_valid():
            writing = writing_form.save(commit=False)
            writing.author = request.user
            writing.save()
            return redirect('board:detail', writing.pk)
    else:
        writing_form = WritingForm()
    context = {
        'writing_form': writing_form,
    }
    return render(request, 'board/writing.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, board_pk):
    """update writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    if request.method == 'POST':
        writing_form = WritingForm(request.POST, instance=writing)
        if writing_form.is_valid():
            writing = writing_form.save()
            return redirect('board:detail', writing.pk)
    else:
        writing_form = WritingForm(instance=writing)
    context = {
        'writing_form': writing_form,
    }
    return render(request, 'board/writing.html', context)


@login_required
@require_safe
def delete(request, board_pk):
    """delete writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    if writing.author == request.user:
        writing.delete()
    return redirect('board:index')


@login_required
@require_safe
def detail(request, board_pk):
    """detail writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    context = {
        'writing': writing,
    }
    return render(request, 'board/detail.html', context)

board/views/comment_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import (require_http_methods, require_POST,
                                          require_safe)
from ..forms import WritingForm, CommentForm
from ..models import Writing, Comment


@login_required
@require_POST
def create(request, board_pk):
    """create comment

    Args:
        request ([type]): [description]
        writing_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.author = request.user
        comment.writing = Writing.objects.get(pk=board_pk)
        comment.save()        
    return redirect('board:detail', board_pk)

board/views/writing_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import (require_http_methods, require_POST,
                                          require_safe)

from ..forms import WritingForm, CommentForm
from ..models import Writing, Comment


# board create, read
@require_safe
def index(request):
    """list writing

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    writings = Writing.objects.order_by('-pk')
    page = request.GET.get('page', '1')
    paginator = Paginator(writings, 20)
    page_obj = paginator.get_page(page)
    context = {
        'writings': page_obj,
    }
    return render(request, 'board/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    """create writing

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    if request.method == 'POST':
        writing_form = WritingForm(request.POST)
        if writing_form.is_valid():
            writing = writing_form.save(commit=False)
            writing.author = request.user
            writing.save()
            return redirect('board:detail', writing.pk)
    else:
        writing_form = WritingForm()
    context = {
        'writing_form': writing_form,
    }
    return render(request, 'board/writing.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, board_pk):
    """update writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    if request.method == 'POST':
        writing_form = WritingForm(request.POST, instance=writing)
        if writing_form.is_valid():
            writing = writing_form.save()
            return redirect('board:detail', writing.pk)
    else:
        writing_form = WritingForm(instance=writing)
    context = {
        'writing_form': writing_form,
    }
    return render(request, 'board/writing.html', context)


@login_required
@require_safe
def delete(request, board_pk):
    """delete writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    if writing.author == request.user:
        writing.delete()
    return redirect('board:index')


@login_required
@require_safe
def detail(request, board_pk):
    """detail writing

    Args:
        request ([type]): [description]
        board_pk ([type]): [description]

    Returns:
        [type]: [description]
    """
    writing = get_object_or_404(Writing, pk=board_pk)
    comment_form = CommentForm()
    comments = writing.comments.all()
    context = {
        'writing': writing,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'board/detail.html', context)

board/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
  <h2>{{ writing.title }}</h2>
  <p class="mb-0">작성자: {{ writing.author }}</p>
  <p style="font-size: 0.75rem;" class="text-right mb-0">최초 작성일: {{ writing.created_at|date:'Y-m-d H:i' }}</p>
  <p style="font-size: 0.75rem;" class="text-right">최종 수정일: {{ writing.updated_at|date:'Y-m-d H:i' }}</p>
  <hr>
  <p>{{ writing.content }}</p>
  <div class="text-right">
    <a class="btn btn-dark" href="{% url 'board:index' %}">글 목록</a>
    {% if request.user == writing.author %}
      <a class="btn btn-dark" href="{% url 'board:delete' writing.pk %}">삭제</a>
    {% endif %}
  </div>
  <hr>
  <div><i class="fas fa-comments mb-3" style="font-size:1.5rem;"></i>
    <ul class="list-group">
      {% for comment in comments %}
        <li class="list-group-item">{{ comment.author }}: {{ comment.content }}
          <div class="text-right">
            <button class="btn"><i class="fas fa-trash-alt"></i></button>
            <button class="btn"><i class="fas fa-reply"></i></button>
          </div>
        </li>
      {% endfor %}
    </ul>
    <br>
    <form action="{% url 'board:comment_create' writing.pk %}" method="POST" class="">
      {% csrf_token %}
      <div class="row align-items-center my-1">
        <input type="text" name="content" id="content" class="form-control col mr-1">
        <input type="submit" value="댓글 쓰기" class="btn btn-dark col-1">
      </div>
    </form>
  </div>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
  <table class="table text-center table-striped border">
    <thead>
      <tr>
        <th scope="col">번호</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for writing in writings %}
        <tr>
          <th scope="row">
            {{ writing.id }}
          </th>
          <td class="text-left"><a class="text-body text-decoration-none" href="{% url 'board:detail' writing.pk %}">{{ writing.title }}</a></td>
          <td>{{ writing.author.username }}</td>
          <td class="text-right">{{ writing.created_at|date:'Y년 m월 d일 H:i' }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <p class="text-right"><a class="btn btn-dark" href="{% url 'board:create' %}">글 작성하기</a> </p>
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if writings.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ writings.previous_page_number }}">이전</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in writings.paginator.page_range %}
      <!-- 양 옆으로 5개 페이지씩 표시 -->
      {% if page_number >= writings.number|add:-5 and page_number <= writings.number|add:5 %}
        {% if page_number == writings.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if writings.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ writings.next_page_number }}">다음</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
    {% endif %}
  </ul>
{% endblock %}

board/templates/board/writing.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ writing_form.as_p }}
    <div class="text-right">
      <input class="btn btn-dark" type="submit" value="글 작성하기">
      <a class="btn btn-dark" href="javascript:history.back()">뒤로 가기</a>
    </div>
  </form>
{% endblock %}