accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.profile, name='profile'),
]

board/urls.py
from django.urls import path

from .views import writing_views, comment_views

app_name = 'board'
urlpatterns = [
    # writing_views
    path('', writing_views.index, name='index'),
    path('create/', writing_views.create, name='create'),
    path('<int:board_pk>/', writing_views.detail, name='detail'),
    path('<int:board_pk>/update/', writing_views.update, name='update'),
    path('<int:board_pk>/delete/', writing_views.delete, name='delete'),

    # comment_views
    path('<int:board_pk>/comment/create', comment_views.create, name='comment_create'),
    # path('<int:board_pk>/comment/<int:comment_pk>/delete/', comment_views.comment_delete, name='comment_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from index import views as index_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_footer.html
<footer class="fixed-bottom bg-dark">
  <p class="text-secondary text-center m-1">No Copyright, <b>Just Copyleft</b></p>
</footer>

templates/_navbar.html
<nav class="sticky-top navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <a class="navbar-brand" href="{% url 'index' %}">Powerticket</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-between px-3" id="navbarNav">
    <ul class="navbar-nav">
      <li id="js-home" class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li id="js-board" class="nav-item">
        <a class="nav-link" href="{% url 'board:index' %}">Py-board</a>
      </li>
      <li id="js-data" class="nav-item">
        <a class="nav-link disabled" href="">Py-data</a>
      </li>
      <li id="js-crawler" class="nav-item">
        <a class="nav-link disabled" href="">Py-crawler</a>
      </li>
      <li id="js-about" class="nav-item">
        <a class="nav-link disabled" href="">About</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
        <li id="js-profile" class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' request.user.pk %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
        </li>
      {% else %}
        <li id="js-signup" class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
        </li>
        <li id="js-login" class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
<script>
  const path = window.location.pathname
  const navList = ['board', 'data', 'crawler']
  if (path === '/') {
    const li = document.querySelector('#js-home')
    li.classList.add('active')
  } else {
    navList.some(selector => {
      if (path.includes(selector)) {
        const li = document.querySelector(`#js-${selector}`)
        li.classList.add('active')
        return
      }
    })
  }
</script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>
<body>
  {% include '_navbar.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% include '_footer.html' %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>